CREATE TABLE "Users" (
	"name" text NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"is_active" text DEFAULT 'true',
	"role" text DEFAULT 'user',
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"updated_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"deleted_at" timestamp,
	"deleted_by" integer,
	"last_ip" integer,
	CONSTRAINT "Users_email_unique" UNIQUE("email")
);
